version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./dataset:/dataset
      - ./model:/model

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes: 
      - ./dataset:/dataset
      - ./model:/model
    depends_on:
      - api